
server:
  port: 8848
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/rainblog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      test-on-borrow: true
      test-while-idle: true
  devtools:
    restart:
      enabled: false

  thymeleaf:
    #false 表示不使用缓存，改了页面会实时更新
    cache: false

# 打印sql
logging:
  level:
    cn.yudianxx.system.mapper: info

qiniuyun:
  AccessKey: UrQy3c4liy9FkDbqYqNbGGZu-llJyZB_NcNp8ssW
  SecretKey: D733cwC6teyDcT08aijMuKIEDGU4WSGm9GtREe6n
  BucketName: rain-blog-yudianxx-pro
  url: rainyudianxx.baimuxym.cn/

image:
  file:
    directory: /var/www/web/project_Blog/images/