server:
  port: 8840
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: @spring.profiles.active@

  devtools:
    restart:
      enabled: true

#以下都是默认的配置，类似于mvc项目的配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存



  #文件上传相关设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: cn.yudianxx.system.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  global-config:
    banner: false

