server:
  port: 8848
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: @spring.profiles.active@

  devtools:
    restart:
      enabled: true
  #thymeleaf模板引擎
  thymeleaf:
    #false 表示不使用缓存，改了页面会实时更新
    cache: false

  #文件上传相关设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: cn.yudianxx.system.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
